import express from 'express';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import path from 'path';
import fs from 'fs';
import dotenv from 'dotenv';

dotenv.config();

const isProd = process.env.NODE_ENV === 'production';
const PORT = 3000;

async function startServer() {
  const app = express();
  app.use(express.json({ limit: '10mb' }));

  // Initialize Gemini Client
  const apiKey = process.env.GEMINI_API_KEY;
  const ai = apiKey ? new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  }) : null;

  // Middleware to check if Gemini client is initialized
  const requireAi = (req: express.Request, res: express.Response, next: express.NextFunction) => {
    if (!ai) {
      return res.status(500).json({
        error: 'Gemini API key is not configured. Please add GEMINI_API_KEY in Settings > Secrets.'
      });
    }
    next();
  };

  // API Route: Generate Text / Chat (supports custom configurations)
  app.post('/api/gemini/generate', requireAi, async (req, res) => {
    try {
      const { prompt, config, model = 'gemini-3.5-flash' } = req.body;
      
      const response = await ai!.models.generateContent({
        model: model,
        contents: prompt,
        config: config || {},
      });

      res.json({ text: response.text });
    } catch (error: any) {
      console.error('Error in /api/gemini/generate:', error);
      res.status(500).json({ error: error.message || 'An error occurred during text generation.' });
    }
  });

  // API Route: Chat Stream (Server-Sent Events)
  app.post('/api/gemini/stream', requireAi, async (req, res) => {
    const { prompt, config, model = 'gemini-3.5-flash' } = req.body;
    
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    try {
      const responseStream = await ai!.models.generateContentStream({
        model: model,
        contents: prompt,
        config: config || {},
      });

      for await (const chunk of responseStream) {
        if (chunk.text) {
          res.write(`data: ${JSON.stringify({ text: chunk.text })}\n\n`);
        }
      }
      res.write('data: [DONE]\n\n');
      res.end();
    } catch (error: any) {
      console.error('Error in stream:', error);
      res.write(`data: ${JSON.stringify({ error: error.message || 'Stream error' })}\n\n`);
      res.end();
    }
  });

  // API Route: Generate Images
  app.post('/api/gemini/image', requireAi, async (req, res) => {
    try {
      const { prompt, aspectRatio = '1:1', imageSize = '1K', model = 'gemini-3.1-flash-lite-image' } = req.body;

      const response = await ai!.models.generateContent({
        model: model,
        contents: prompt,
        config: {
          imageConfig: {
            aspectRatio,
            imageSize,
          },
        },
      });

      let imageBase64 = '';
      let textResponse = '';

      const parts = response.candidates?.[0]?.content?.parts || [];
      for (const part of parts) {
        if (part.inlineData) {
          imageBase64 = part.inlineData.data;
        } else if (part.text) {
          textResponse += part.text;
        }
      }

      if (imageBase64) {
        res.json({ image: `data:image/png;base64,${imageBase64}`, text: textResponse });
      } else {
        res.status(400).json({ error: 'No image data was generated by the model.', text: textResponse });
      }
    } catch (error: any) {
      console.error('Error in /api/gemini/image:', error);
      res.status(500).json({ error: error.message || 'An error occurred during image generation.' });
    }
  });

  // API Route: Structured Extraction (JSON schema)
  app.post('/api/gemini/extract', requireAi, async (req, res) => {
    try {
      const { text, schema, promptDescription } = req.body;

      const response = await ai!.models.generateContent({
        model: 'gemini-3.5-flash',
        contents: `Analyze the following text and extract structured information according to the requested rules.\n\nText: ${text}`,
        config: {
          systemInstruction: promptDescription || "You are an expert data extraction assistant. Extract structured data accurately.",
          responseMimeType: "application/json",
          responseSchema: schema,
        },
      });

      res.json({ data: JSON.parse(response.text || '{}') });
    } catch (error: any) {
      console.error('Error in /api/gemini/extract:', error);
      res.status(500).json({ error: error.message || 'An error occurred during data extraction.' });
    }
  });

  // Setup Vite or Static File Serving
  if (!isProd) {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'custom',
    });
    
    app.use(vite.middlewares);

    app.use('*', async (req, res, next) => {
      const url = req.originalUrl;
      try {
        let template = fs.readFileSync(path.resolve('./index.html'), 'utf-8');
        template = await vite.transformIndexHtml(url, template);
        res.status(200).set({ 'Content-Type': 'text/html' }).end(template);
      } catch (e) {
        vite.ssrFixStacktrace(e as Error);
        next(e);
      }
    });
  } else {
    const outDir = fs.existsSync(path.resolve('./docs')) ? './docs' : './dist';
    app.use(express.static(path.resolve(outDir)));
    app.get('*', (req, res) => {
      res.sendFile(path.resolve(outDir, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server is running at http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error('Failed to start server:', err);
});
